# Generated by Django 6.0.4 on 2026-05-01 21:25

import utils.uuid_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
