# Generated by Django 6.0.6 on 2026-06-27 01:22

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=users.models.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
