# Generated by Django 6.0.6 on 2026-06-27 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_qr_refresh_interval'),
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='organization.organization'),
        ),
    ]
