services:
  - type: web
    plan: free
    name: punctuahr
    runtime: python
    buildCommand: chmod a+x build.sh && ./build.sh
    startCommand: gunicorn puntua_backend.wsgi:application
  
    envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: puntua_backend.settings
    - key: ENV
      value: prod
    - key: BACKEND_URL
      value: https://punctuahr.onrender.com

    