# Generated by Django 6.0.6 on 2026-06-27 12:36

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=organization.models.generate_org_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('whatsapp_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
