# Generated by Django 6.0.6 on 2026-06-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='allow_ussd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='allowed_radius',
            field=models.FloatField(default=100.0, help_text='Allowed radius in meters'),
        ),
        migrations.AddField(
            model_name='organization',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='qr_refresh_interval',
            field=models.IntegerField(default=10, help_text='QR refresh interval in seconds'),
        ),
        migrations.AddField(
            model_name='organization',
            name='require_gps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='require_qr',
            field=models.BooleanField(default=False),
        ),
    ]
