# Generated by Django 6.0.6 on 2026-06-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_allow_remote_organization_allow_ussd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='qr_refresh_interval',
            field=models.IntegerField(default=40, help_text='QR refresh interval in seconds'),
        ),
    ]
