# Generated by Django 6.0.6 on 2026-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_qr_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Daily operational close time', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Daily operational start time', null=True),
        ),
    ]
