# Generated by Django 6.0.6 on 2026-06-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_close_time_organization_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location_data',
            field=models.JSONField(blank=True, help_text='Metadata from geolocation API', null=True),
        ),
    ]
