# Generated by Django 6.0.6 on 2026-06-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_location_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='close_time',
        ),
        migrations.AddField(
            model_name='organization',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Daily operational duration in hours', null=True),
        ),
    ]
