# Generated by Django 6.0.6 on 2026-06-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_organization_close_time_organization_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_qr_session',
            field=models.BooleanField(default=False),
        ),
    ]
