# Generated by Django 6.0.6 on 2026-06-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organization_auto_qr_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='use_social',
            field=models.BooleanField(default=False),
        ),
    ]
