# Generated by Django 6.0.6 on 2026-06-27 16:00

import django.db.models.deletion
import shift.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_organization_allow_remote_organization_allow_ussd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.CharField(default=shift.models.generate_shift_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_period', models.IntegerField(default=15, help_text='Late check-in tolerance in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organization.organization')),
            ],
        ),
    ]
