# Generated by Django 6.0.6 on 2026-06-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shift.shift'),
        ),
    ]
