# Generated by Django 6.0.6 on 2026-06-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active/Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
