# Generated by Django 6.0.6 on 2026-06-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
