# Generated by Django 6.0.6 on 2026-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_attach',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='link_attach',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='file_attach',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='link_attach',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
