# Generated by Django 6.0.6 on 2026-06-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR Code'), ('social_wa', 'WhatsApp'), ('social_tl', 'Telegram')], default='manual', max_length=20),
        ),
    ]
